-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "latitude_in" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "latitude_out" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "longitude_in" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "longitude_out" SET DATA TYPE DECIMAL(65,30);
